### ISSUE TITLE
Unnecssary junk in your projects

### ISSUE THREAD

**Issue by marc2k3** [grimes2/foo_startpaused#1]
Using ,rc and resource.hpp from my playlist fix repo is beyond stupid. I used them for dialogs. You have no dialogs and even if you did, you'd want your own files, not a 3rd party.

And you don't need SDK helpers/libPPUI/WTL for anything either. You only need SDK/component client/pfc like my simpler foo_run_main component...

![image](https://user-images.githubusercontent.com/62050527/197336262-5da38be0-17a0-4d03-a002-55883be8744f.png)

https://github.com/marc2k3/foo_run_main/tree/main/src

**Comment by grimes2** [comment]
Thanks. Junk removed.
